baseURL: https://minocrafft.io/
languageCode: ko-kr
languageName: 한국어

title: AtoZ - devlog
theme: AtoZ
copyright: "&copy; 2023 Minho Kim Powered by [Hugo](https://gohugo.io/)"

author:
  name: Minho Kim
  email: minocrafft@gmail.com
  image: "/images/author.jpeg"
  comments: "I don't know anything."

menu:
  main:
    - weight: 1
      identifier: home
      pre: ""
      post: ""
      name: Home
      url: /
    - weight: 2
      identifier: posts
      pre: ""
      post: ""
      name: Blog
      url: /blog/
    - weight: 3
      identifier: categories
      pre: ""
      post: ""
      name: Categories
      url: /categories/
    - weight: 4
      identifier: tags
      pre: ""
      post: ""
      name: Tags
      url: /tags/
    - weight: 5
      identifier: archives
      pre: ""
      post: ""
      name: Archives
      url: /archives/

  social:
    - name: "Email"
      url: "mailto:minocrafft@gmail.com"
      pre: "<i class='fas fa-fw fa-envelope'></i>"
    - name: "Github"
      url: "https://github.com/minocrafft"
      pre: "<i class='fab fa-github'></i>"
    - name: "Instagram"
      url: "https://instagram.com/mainho._"
      pre: "<i class='fab fa-instagram'></i>"
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/minocraft/"
      pre: "<i class='fab fa-linkedin'></i>"

  footer:
    # - has_social: true
    - name: "About"
      url: "/about/"
    - name: "Contact"
      # url: "mailto:minhub6@gmail.com"
      url: "/contact"

params:
  description: "A to Z of development"
  favicon: images/favicon.png
  about: "/images/about.jpeg"

googleAnalytics: ""
